---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4129941346-omVsiIGU2h7GvOMC8TB5VE9LPMTyER5v5p8MEJs
:access_token_secret: MzF5Bnc8XrjnPER8tBThIupPrQqSwkMwm3zLqE6UN9kHo
